### ISSUE TITLE
Mark compatibility with Symphony 2.5+

### ISSUE THREAD

**Issue by jensscherbl** [symphonycms/profiledevkit#5]
Shouldn't the `max`-attribute be `2.x.x` instead of `2.5.x`? With our switch to semantic versioning, no breaking changes are expected until *3.0.0*.

Only opening this issue here, but it's the same with all the other first party extensions.

**Comment by nitriques** [comment]
> Shouldn't the max-attribute be 2.x.x instead of 2.5.x?

Yup, done.
